### ISSUE TITLE
[ToDo] Some fixes

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [MiguelNdeCarvalho/docker-baseimage-archlinux#6]
- [x] Remove abc user from being able to use `sudo` passwordless
- [x] Update the docker image in the begin
- [x] Create folder `/config` and `/default`
- [x] Make `/config` folder as `abc` home and disable shell
- [x] Delete the cache on the end of the image
